name: Deno CI

on:
  workflow_call:
    inputs:
      deno-version:
        description: "Deno version"
        type: string
        default: "v2.x"
      run-tests:
        description: "Run deno test"
        type: boolean
        default: false

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Lint
        run: deno lint

      - name: Format check
        run: deno fmt --check

      - name: Test
        if: ${{ inputs.run-tests }}
        run: deno test
